import { access, chmod, mkdir, readFile, writeFile } from 'node:fs/promises'
import { constants as fsConstants } from 'node:fs'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

/** Afterimage package root (where package.json + dist/ live). */
export function lucidPackageRoot(): string {
  const here = path.dirname(fileURLToPath(import.meta.url))
  // Compiled: dist/src/runtime/cursor → 4 levels up
  // Source ts executed oddly: src/runtime/cursor → 3 levels up
  if (here.split(path.sep).includes('dist')) {
    return path.resolve(here, '../../../..')
  }
  return path.resolve(here, '../../..')
}

function hookEntryPath(packageRoot: string): string {
  return path.join(packageRoot, 'dist', 'src', 'runtime', 'cursor', 'hook-cli.js')
}

async function exists(filePath: string): Promise<boolean> {
  try {
    await access(filePath, fsConstants.F_OK)
    return true
  } catch {
    return false
  }
}

export type InstallCursorHooksResult = {
  hooksJsonPath: string
  observeScriptPath: string
  hookEntry: string
  mergedEvents: string[]
}

/**
 * Install Afterimage Cursor hooks into a project so normal Agent chats are observed.
 * Merges with any existing `.cursor/hooks.json` entries.
 */
export async function installCursorHooks(options: {
  projectRoot: string
  /** Override Afterimage package root (tests). */
  packageRoot?: string
}): Promise<InstallCursorHooksResult> {
  const projectRoot = path.resolve(options.projectRoot)
  const packageRoot = options.packageRoot ?? lucidPackageRoot()
  const hookEntry = hookEntryPath(packageRoot)

  if (!(await exists(hookEntry))) {
    throw new Error(
      `Afterimage hook entry missing at ${hookEntry}. Run \`npm run build\` in the Afterimage package first.`,
    )
  }

  const cursorDir = path.join(projectRoot, '.cursor')
  const hooksDir = path.join(cursorDir, 'hooks')
  await mkdir(hooksDir, { recursive: true })

  const observeScriptPath = path.join(hooksDir, 'lucid-observe.mjs')
  const observeScript = `#!/usr/bin/env node
/**
 * Afterimage Cursor observe hook — keep prompting normally.
 * Generated by \`afterimage attach cursor\`.
 */
import { pathToFileURL } from 'node:url'

const entry = ${JSON.stringify(hookEntry)}
const mod = await import(pathToFileURL(entry).href)
await mod.runCursorHookCli()
`
  await writeFile(observeScriptPath, observeScript, 'utf8')
  await chmod(observeScriptPath, 0o755)

  const hooksJsonPath = path.join(cursorDir, 'hooks.json')
  const command = '.cursor/hooks/lucid-observe.mjs'
  const lucidEvents = [
    'sessionStart',
    'beforeSubmitPrompt',
    'afterFileEdit',
    'postToolUse',
    'stop',
  ] as const

  let existing: { version?: number; hooks?: Record<string, Array<Record<string, unknown>>> } =
    { version: 1, hooks: {} }
  if (await exists(hooksJsonPath)) {
    try {
      existing = JSON.parse(await readFile(hooksJsonPath, 'utf8')) as typeof existing
    } catch {
      existing = { version: 1, hooks: {} }
    }
  }

  const hooks = { ...(existing.hooks ?? {}) }
  for (const eventName of lucidEvents) {
    const list = Array.isArray(hooks[eventName]) ? [...hooks[eventName]!] : []
    const already = list.some(
      (item) =>
        typeof item.command === 'string' &&
        (item.command.includes('lucid-observe') || item.command === command),
    )
    if (!already) {
      list.push({ command })
    }
    hooks[eventName] = list
  }

  const next = {
    version: existing.version ?? 1,
    hooks,
  }
  await writeFile(hooksJsonPath, `${JSON.stringify(next, null, 2)}\n`, 'utf8')

  // Remember install metadata under the active store dir.
  const preferredDir = path.join(projectRoot, '.afterimage')
  const legacyDir = path.join(projectRoot, '.lucid')
  const metaDir = (await exists(preferredDir))
    ? preferredDir
    : (await exists(legacyDir))
      ? legacyDir
      : preferredDir
  await mkdir(metaDir, { recursive: true })
  await writeFile(
    path.join(metaDir, 'cursor.json'),
    `${JSON.stringify(
      {
        attachedAt: new Date().toISOString(),
        hookEntry,
        packageRoot,
        observeScript: observeScriptPath,
      },
      null,
      2,
    )}\n`,
    'utf8',
  )

  return {
    hooksJsonPath,
    observeScriptPath,
    hookEntry,
    mergedEvents: [...lucidEvents],
  }
}

/** Resolve the hook entry URL for dynamic import helpers. */
export function hookEntryFileUrl(packageRoot = lucidPackageRoot()): string {
  return pathToFileURL(hookEntryPath(packageRoot)).href
}
