export {
  getStaff,
  listHospitalStaff,
  listStaffForApi,
  projectHospitalCare,
  buildLabTests,
  specialistForTreatmentTarget,
  staffForDepartment,
  type HospitalCareProjection,
  type HospitalCareTeam,
  type HospitalLabTest,
  type HospitalStaffMember,
  type HospitalStaffStage,
  type HospitalStaffStatus,
  type LabTestResult,
} from './staff/index.ts'
